"""4thchange

Revision ID: cf298659ed03
Revises: 029bbce2fa4c
Create Date: 2024-09-11 10:43:53.455043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf298659ed03'
down_revision = '029bbce2fa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adult_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('child_price', sa.Integer(), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('child_price')
        batch_op.drop_column('adult_price')

    # ### end Alembic commands ###
